spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  flyway:
    locations: classpath:db/migration,classpath:db/seed/common
    clean-disabled: true

logging:
  level:
    org.hibernate.SQL: info

app:
  swagger:
    username: ${SWAGGER_DOCS_USERNAME}
    password: ${SWAGGER_DOCS_PASSWORD}