-- Baseline schema extracted from init.sql.
-- Seed data is managed separately under db/seed.


CREATE TABLE auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20),
    password VARCHAR(255),
    login_type VARCHAR(20) NOT NULL,
    provider_id VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    version VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content_key VARCHAR(255),
    required BOOLEAN NOT NULL,
    effective_at TIMESTAMP NOT NULL
);

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id BIGINT NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    birth_year INTEGER,
    gender VARCHAR(20),
    profile_image_key VARCHAR(255),
    bio VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_members_auth FOREIGN KEY (auth_id) REFERENCES auth (id)
);

CREATE TABLE auth_terms_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id BIGINT NOT NULL,
    terms_id BIGINT NOT NULL,
    agreed BOOLEAN NOT NULL,
    agreed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_auth_terms_agreements_auth FOREIGN KEY (auth_id) REFERENCES auth (id),
    CONSTRAINT fk_auth_terms_agreements_terms FOREIGN KEY (terms_id) REFERENCES terms (id)
);

CREATE TABLE leagues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE stadiums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);

CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    short_name VARCHAR(20),
    emblem_image_key VARCHAR(255)
);

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id BIGINT NOT NULL,
    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,
    stadium_id BIGINT NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    deadline DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    home_score INTEGER,
    away_score INTEGER,
    CONSTRAINT fk_games_league FOREIGN KEY (league_id) REFERENCES leagues (id),
    CONSTRAINT fk_games_home_team FOREIGN KEY (home_team_id) REFERENCES teams (id),
    CONSTRAINT fk_games_away_team FOREIGN KEY (away_team_id) REFERENCES teams (id),
    CONSTRAINT fk_games_stadium FOREIGN KEY (stadium_id) REFERENCES stadiums (id)
);

CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    matched_at TIMESTAMP,
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_matches_game FOREIGN KEY (game_id) REFERENCES games (id)
);

CREATE TABLE match_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    match_id BIGINT,
    party_size INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    applied_at TIMESTAMP NOT NULL,
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_match_applications_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_match_applications_game FOREIGN KEY (game_id) REFERENCES games (id),
    CONSTRAINT fk_match_applications_match FOREIGN KEY (match_id) REFERENCES matches (id)
);

CREATE TABLE match_participants (
    match_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    application_id BIGINT,
    response VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP NOT NULL,
    PRIMARY KEY (match_id, member_id),
    CONSTRAINT fk_match_participants_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_match_participants_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_match_participants_application FOREIGN KEY (application_id) REFERENCES match_applications (id)
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    sender_id BIGINT,
    text VARCHAR(1000) NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'text',
    sent_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_messages_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_chat_messages_sender FOREIGN KEY (sender_id) REFERENCES members (id)
);

CREATE TABLE member_location_verifications (
    member_id BIGINT PRIMARY KEY,
    verified BOOLEAN NOT NULL,
    address VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    verified_at TIMESTAMP,
    CONSTRAINT fk_member_location_verifications_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE member_preferences (
    member_id BIGINT PRIMARY KEY,
    gender_pref VARCHAR(20),
    age_pref VARCHAR(20),
    smoking_pref VARCHAR(20),
    distance_km INTEGER NOT NULL,
    CONSTRAINT fk_member_preferences_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE member_stats (
    member_id BIGINT PRIMARY KEY,
    match_count INTEGER NOT NULL,
    rating DOUBLE PRECISION NOT NULL,
    trust_score INTEGER NOT NULL,
    coupon_count INTEGER NOT NULL,
    priority_pass_count INTEGER NOT NULL,
    CONSTRAINT fk_member_stats_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE member_styles (
    member_id BIGINT PRIMARY KEY,
    favorite_team_id BIGINT,
    personality VARCHAR(50),
    talk_style VARCHAR(50),
    smoking_status VARCHAR(50),
    CONSTRAINT fk_member_styles_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_member_styles_favorite_team FOREIGN KEY (favorite_team_id) REFERENCES teams (id)
);

CREATE TABLE member_watch_styles (
    member_id BIGINT NOT NULL,
    watch_style VARCHAR(50) NOT NULL,
    PRIMARY KEY (member_id, watch_style),
    CONSTRAINT fk_member_watch_styles_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE notification_settings (
    member_id BIGINT PRIMARY KEY,
    match_request BOOLEAN NOT NULL,
    match_schedule BOOLEAN NOT NULL,
    chat BOOLEAN NOT NULL,
    review BOOLEAN NOT NULL,
    marketing BOOLEAN NOT NULL,
    CONSTRAINT fk_notification_settings_member FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    application_id BIGINT,
    match_id BIGINT,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(1000),
    target_kind VARCHAR(50),
    read BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notifications_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_notifications_application FOREIGN KEY (application_id) REFERENCES match_applications (id),
    CONSTRAINT fk_notifications_match FOREIGN KEY (match_id) REFERENCES matches (id)
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL,
    target_member_id BIGINT NOT NULL,
    match_id BIGINT,
    reason VARCHAR(50) NOT NULL,
    detail VARCHAR(1000),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) REFERENCES members (id),
    CONSTRAINT fk_reports_target_member FOREIGN KEY (target_member_id) REFERENCES members (id),
    CONSTRAINT fk_reports_match FOREIGN KEY (match_id) REFERENCES matches (id)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    target_member_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment VARCHAR(1000),
    CONSTRAINT fk_reviews_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_reviews_reviewer FOREIGN KEY (reviewer_id) REFERENCES members (id),
    CONSTRAINT fk_reviews_target_member FOREIGN KEY (target_member_id) REFERENCES members (id)
);

CREATE TABLE review_tags (
    review_id BIGINT NOT NULL,
    tag VARCHAR(50) NOT NULL,
    PRIMARY KEY (review_id, tag),
    CONSTRAINT fk_review_tags_review FOREIGN KEY (review_id) REFERENCES reviews (id)
);
