-- BaseTimeEntity(createdAt/updatedAt/createdBy/updatedBy) 상속을 모든 JPA 엔티티에
-- 적용하면서 필요해진 스키마 정리. AuditLogEntity(audit_logs)는 불변 로그라
-- occurred_at/created_at(DB DEFAULT, insertable=false)만으로 충분해 이번 통일 대상에서 제외.

-- 이미 created_at(NOT NULL)/updated_at을 갖고 있던 테이블: created_by/updated_by만 추가.
ALTER TABLE members ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE members ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE auth ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE auth ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE matches ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE matches ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE reports ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE reports ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

-- created_at/updated_at이 전혀 없던 테이블: 4개 컬럼 전부 추가.
-- created_at은 기존 행 백필을 위해 DEFAULT CURRENT_TIMESTAMP를 둔다.

ALTER TABLE member_withdrawal_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE member_withdrawal_logs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE member_withdrawal_logs ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE member_withdrawal_logs ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE terms ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE terms ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE terms ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE terms ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE auth_terms_agreements ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE auth_terms_agreements ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE auth_terms_agreements ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE auth_terms_agreements ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE leagues ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE stadiums ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE stadiums ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE stadiums ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE stadiums ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE teams ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE games ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE games ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE games ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE games ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE match_applications ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE match_applications ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE match_applications ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE match_applications ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE match_participants ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE match_participants ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE match_participants ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE match_participants ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE member_location_verifications ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE member_location_verifications ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE member_location_verifications ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE member_location_verifications ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE member_preferences ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE member_preferences ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE member_preferences ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE member_preferences ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE member_stats ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE member_stats ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE member_stats ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE member_stats ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE member_styles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE member_styles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE member_styles ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE member_styles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE member_watch_styles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE member_watch_styles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE member_watch_styles ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE member_watch_styles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE notification_settings ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE banners ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE banners ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE faqs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE avatar_presets ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE avatar_presets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE avatar_presets ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE avatar_presets ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE content_assets ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE content_assets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE content_assets ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE content_assets ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE reviews ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

ALTER TABLE review_tags ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE review_tags ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
ALTER TABLE review_tags ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE review_tags ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

