ALTER TABLE terms
    ADD COLUMN IF NOT EXISTS content TEXT,
    ADD COLUMN IF NOT EXISTS valid_days INTEGER;

ALTER TABLE teams
    ADD COLUMN IF NOT EXISTS primary_color_hex VARCHAR(7);

CREATE TABLE IF NOT EXISTS banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(100) NOT NULL,
    image_key VARCHAR(255) NOT NULL,
    link_url VARCHAR(500),
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    starts_at TIMESTAMP,
    ends_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL,
    question VARCHAR(255) NOT NULL,
    answer TEXT NOT NULL,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS avatar_presets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    image_key VARCHAR(255) NOT NULL,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS content_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(100) NOT NULL,
    object_key VARCHAR(255) NOT NULL,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_content_assets_type_code UNIQUE (type, code)
);

CREATE INDEX IF NOT EXISTS idx_terms_code_effective_at ON terms (code, effective_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_terms_agreements_auth_terms ON auth_terms_agreements (auth_id, terms_id, agreed_at DESC);
CREATE INDEX IF NOT EXISTS idx_banners_active_order ON banners (active, display_order);
CREATE INDEX IF NOT EXISTS idx_faqs_active_order ON faqs (active, display_order);
CREATE INDEX IF NOT EXISTS idx_avatar_presets_active_order ON avatar_presets (active, display_order);
CREATE INDEX IF NOT EXISTS idx_content_assets_active_order ON content_assets (active, type, display_order);
